### ISSUE TITLE
DataTerm#append does not function

### ISSUE THREAD

**Issue by TheOnlyArtz** [kingsleyh/crystal-rethinkdb#10]
I have a simple row that holds an array, I'm trying to append to this array using 

```crystal
r.db("garden").get("gardens").get(ID.to_s)["thearray"].append({test: ".."}).run(conn)
```

The array stays the same, empty.

**Comment by kingsleyh** [comment]
Thanks - I'll have a look at it

**Comment by kingsleyh** [comment]
does something like this work?

```
r.db("garden").get("gardens").get(ID.to_s).update{|u| {theArray: u.get_field("theArray").append({test: ".."})}  }.run(conn)
```

**Comment by TheOnlyArtz** [comment]
@kingsleyh it works indeed, although it's not as clean as the other drivers, Thank you very much!

**Comment by kingsleyh** [comment]
The shorter methods are not yet implemented - but I'll add it to the list

**Comment by TheOnlyArtz** [comment]
@kingsleyh Sorry for bothering you, I ran into some logical issues, may you please look into this? (I don't want to open a brand new issue since it's more of a question than an issue)

https://forum.crystal-lang.org/t/how-to-serialize-a-struct-from-any-type/1542

**Comment by kingsleyh** [comment]
Hi - There are 2 things you could get back from a query:
* QueryResult
* Cursor

QueryResult is a single item whereas Cursor is many items. This is how you could handle each case:

given a container class such as User:

```
class User
  JSON.mapping(id: String, email: String, name: String)
end
```

and a find method:

```
class UserRepo
  def initialize(@connection : RethinkDB::Connection) ; end

   # the important thing here is the use of `raw`
  def find_by_id(id) : User | Nil
    result = r.table("users").get(id).run(@connection)
    result.raw.nil? ? Nil : User.from_json(result.raw.to_json)   
  end

  # the important thing here is the use of `to_a` and `map`
  def all : Array(User) | Nil
    query = r.table("users").run(@connection)
   case query
   when RethinkDB::Cursor
     query.to_a.map{ |u| User.from_json(u.raw.to_json)  }
   else
     Nil  
  end
end
```

Personally I usually return a container from the db queries using the CRZ functional library:

```
def find_by_id(id) : Result(User, SystemError)
```
and then when I use it later:

```
Result.match user_repo.find_by_id(id), {
  [Ok, user]  => {user: user.to_json},
  [Err, error] => {error: handle_error(error).to_json}
}
```  
}

Using this patterns I can send back on the API the user or the error (after categorising the error and adding an appropriate message for users to see)

Hope that helps

**Comment by TheOnlyArtz** [comment]
This is amazing, cheers!
